name: freshfood
display_name: freshfood
version: 1.0.8
author:
  name: "YBC-Theme"
  email: "pub@prestashop.com"
  url: "http://www.prestashop.com"

meta:
  compatibility:
    from: 1.7.0.0
    to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

assets:
# If you're using this theme as child and you want to load
# the parent theme assets, uncomment this line.
#  use_parent_assets: true

# The following lines are showing how to load assets in your page
# Uncomment and change value to start loading css or js files
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#  js:
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_enable:
      - ps_linklist
      - ps_categoryproducts
      - ps_bestsellers
      - ps_specials
      - ps_newproducts
      - ps_viewedproduct
      - ps_categorytree
    to_reset:
      - ets_mailchimpsync
      - ets_megamenu
      - ets_multilayerslider
      - ets_reviewticker
      - ybc_themeconfig
      - ybc_widget
      - ybc_manufacturer
      - ph_instagram
  hooks:
    modules_to_hook:
      actionAdminControllerSetMedia:
        - dashactivity
        - dashtrends
        - dashgoals
        - graphnvd3
      actionAdminCurrenciesControllerSaveAfter:
        - ps_currencyselector
      actionAdminGroupsControllerSaveAfter:
        - ps_featuredproducts
      actionAdminStoresControllerUpdate_optionsAfter:
        - ps_contactinfo
      actionAttributeDelete:
        - ps_facetedsearch
      actionAttributeGroupDelete:
        - ps_facetedsearch
      actionAttributeGroupSave:
        - ps_facetedsearch
      actionAttributePostProcess:
        - ps_facetedsearch
      actionAttributeSave:
        - ps_facetedsearch
      actionAuthentication:
        - statsdata
      actionCartSave:
        - blockwishlist
      actionCategoryAdd:
        - ps_facetedsearch
      actionCategoryDelete:
        - ps_facetedsearch
      actionCategoryUpdate:
        - ps_facetedsearch
        - ps_mainmenu
        - ps_featuredproducts
      actionCustomerAccountAdd:
        - ps_emailsubscription
        - statsdata
      actionFeatureDelete:
        - ps_facetedsearch
      actionFeatureSave:
        - ps_facetedsearch
      actionFeatureValueDelete:
        - ps_facetedsearch
      actionFeatureValueSave:
        - ps_facetedsearch
      actionObjectCategoryAddAfter:
        - ps_mainmenu
      actionObjectCategoryDeleteAfter:
        - ps_mainmenu
      actionObjectCategoryUpdateAfter:
        - ps_mainmenu
      actionObjectCmsAddAfter:
        - ps_mainmenu
      actionObjectCmsDeleteAfter:
        - ps_mainmenu
      actionObjectCmsUpdateAfter:
        - ps_mainmenu
      actionObjectCustomerAddAfter:
        - dashactivity
      actionObjectCustomerMessageAddAfter:
        - dashactivity
      actionObjectCustomerThreadAddAfter:
        - dashactivity
      actionObjectLanguageAddAfter:
        - ps_banner
      actionObjectManufacturerAddAfter:
        - ps_mainmenu
      actionObjectManufacturerDeleteAfter:
        - ps_mainmenu
      actionObjectManufacturerUpdateAfter:
        - ps_mainmenu
      actionObjectOrderAddAfter:
        - dashactivity
        - dashproducts
      actionObjectOrderReturnAddAfter:
        - dashactivity
      actionObjectProductAddAfter:
        - ps_mainmenu
      actionObjectProductDeleteAfter:
        - ps_viewedproduct
        - ps_mainmenu
      actionObjectProductUpdateAfter:
        - ps_viewedproduct
        - ps_mainmenu
      actionObjectSpecificPriceCoreAddAfter:
        - ps_specials
      actionObjectSpecificPriceCoreDeleteAfter:
        - ps_specials
      actionObjectSpecificPriceCoreUpdateAfter:
        - ps_specials
      actionObjectSupplierAddAfter:
        - ps_mainmenu
      actionObjectSupplierDeleteAfter:
        - ps_mainmenu
      actionObjectSupplierUpdateAfter:
        - ps_mainmenu
      actionOrderStatusPostUpdate:
        - dashtrends
        - ps_bestsellers
      actionProductAdd:
        - ps_categoryproducts
        - ps_featuredproducts
        - ps_newproducts
        - ps_specials
        - ps_bestsellers
      actionProductDelete:
        - ps_categoryproducts
        - ps_featuredproducts
        - ps_newproducts
        - ps_specials
        - ps_bestsellers
      actionProductSave:
        - ps_facetedsearch
      actionProductUpdate:
        - ps_categoryproducts
        - ps_featuredproducts
        - ps_newproducts
        - ps_specials
        - ps_bestsellers
      actionSearch:
        - dashproducts
      actionShopDataDuplication:
        - ps_imageslider
        - ps_mainmenu
      actionUpdateLangAfter:
        - blockreassurance
        - ps_linklist
      additionalCustomerFormFields:
        - ps_emailsubscription
      blogCategoriesBlock:
        - ybc_blog_free
      blogFeaturedPostsBlock:
        - ybc_blog_free
      blogGalleryBlock:
        - ybc_blog_free
      blogNewsBlock:
        - ybc_blog_free
      blogPopularPostsBlock:
        - ybc_blog_free
      blogSearchBlock:
        - ybc_blog_free
      blogSidebar:
        - ybc_blog_free
      blogSlidersBlock:
        - ybc_blog_free
      blogTagsBlock:
        - ybc_blog_free
      dashboardData:
        - dashactivity
        - dashtrends
        - dashgoals
        - dashproducts
      dashboardZoneOne:
        - dashactivity
      dashboardZoneTwo:
        - dashtrends
        - dashgoals
        - dashproducts
      displayAdminAfterHeader:
        - welcome
      displayAdminCustomers:
        - blockwishlist
      displayAdminNavBarBeforeEnd:
        - welcome
      displayAdminStatsGraphEngine:
        - graphnvd3
      displayAdminStatsGridEngine:
        - gridhtml
      displayAdminStatsModules:
        - pagesnotfound
        - statsbestcategories
        - statsbestcustomers
        - statsbestproducts
        - statsbestsuppliers
        - statsbestvouchers
        - statscarrier
        - statscatalog
        - statscheckup
        - statsforecast
        - statsnewsletter
        - statspersonalinfos
        - statsproduct
        - statsregistrations
        - statssales
        - statssearch
        - statsstock
      displayBackOfficeHeader:
        - ybc_themeconfig
        - ybc_manufacturer
        - productcomments
        - ets_multilayerslider
        - ets_megamenu
        - ets_reviewticker
        - ets_mailchimpsync
        - welcome
        - ybc_widget
        - ybc_blog_free
        - ph_instagram
        - ~
      displayBeforeBodyClosingTag:
        - statsdata
      displayBlock:
        - ets_megamenu
      displayCrossSellingShoppingCart:
        - ps_featuredproducts
      displayCustomerAccount:
        - blockwishlist
      displayFooter:
        - ps_contactinfo
        - ps_linklist
        - ps_emailsubscription
        - ybc_themeconfig
        - ets_reviewticker
        - ybc_widget
        - ybc_blog_free
        - ph_instagram
      displayFooterBefore:
        - ps_socialfollow
      displayFooterProduct:
        - ps_viewedproduct
        - ps_categoryproducts
      ybcInstagram:
        - ph_instagram
      displayHome:
        - ets_multilayerslider
        - ybc_widget
        - ybc_blog_free
        - ybc_manufacturer
        - ps_featuredproducts
        - ps_newproducts
        - ps_specials
        - ps_bestsellers
      displayLeftColumn:
        - ps_facetedsearch
        - ps_categorytree
        - ybc_widget
        - ybc_blog_free
      displayMegaMenu:
        - ets_megamenu
      displayMLS:
        - ets_multilayerslider
      displayMLSConfigs:
        - ets_multilayerslider
      displayMLSLayer:
        - ets_multilayerslider
      displayMLSLayerSort:
        - ets_multilayerslider
      displayMLSSlide:
        - ets_multilayerslider
      displayMLSSlideInner:
        - ets_multilayerslider
      displayMLSSlider:
        - ets_multilayerslider
      displayMMItemBlock:
        - ets_megamenu
      displayMMItemColumn:
        - ets_megamenu
      displayMMItemMenu:
        - ets_megamenu
      displayMultiLayerSlide:
        - ets_multilayerslider
      displayMyAccountBlock:
        - blockwishlist
      displayNav:
        - ybc_widget
      displayNav1:
        - ps_languageselector
        - ps_currencyselector
      displayNav2:
        - ps_customersignin
        - blockwishlist
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayPaymentReturn:
        - ps_checkpayment
        - ps_wirepayment
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - blockwishlist
      displayProductButtons:
        - ps_sharebuttons
      displayProductListFunctionalButtons:
        - blockwishlist
      displayReassurance:
        - blockreassurance
      displayRightColumn:
        - ybc_widget
        - blockwishlist
      displaySearch:
        - ps_searchbar
      displayTop:
        - ps_shoppingcart
        - ps_searchbar
        - ets_megamenu
        - ybc_widget
        - blockwishlist
      displayTopColumn:
        - ybc_widget
      paymentOptions:
        - ps_checkpayment
        - ps_wirepayment
      productcustom:
        - blockwishlist
      productSearchProvider:
        - ps_facetedsearch
      search:
        - statssearch
      tabHome:
        - ps_newproducts
        - ps_featuredproducts
        - ps_bestsellers
        - ps_specials
      tabHomeContent:
        - ps_newproducts
        - ps_featuredproducts
        - ps_bestsellers
        - ps_specials
      ybcBlockSocial:
        - ybc_themeconfig
      ybcCopyright:
        - ybc_themeconfig
      ybcCustom1:
        - ybc_widget
      ybcCustom2:
        - ybc_widget
      ybcCustom3:
        - ybc_widget
      ybccustom4:
        - ybc_manufacturer
        - ybc_widget
      ybcLayoutUpdate:
        - ybc_themeconfig


  image_types:
    cart_default:
      width: 130
      height: 130
      scope: [products]
    small_default:
      width: 270
      height: 270
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 450
      height: 450
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 850
      height: 250
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    search: layout-left-column
    supplier: layout-left-column
    manufacturer: layout-left-column
    contact: layout-full-width

dependencies:
  modules:
    - blockwishlist
    - ets_mailchimpsync
    - ets_megamenu
    - ets_multilayerslider
    - ets_reviewticker
    - productcomments
    - ps_shoppingcart
    - ps_specials
    - ps_categoryproducts
    - ps_bestsellers
    - ps_newproducts
    - ps_viewedproduct
    - ps_sharebuttons
    - ybc_themeconfig
    - ybc_widget
    - ybc_blog_free
    - ybc_manufacturer
    - ps_featuredproducts
    - ph_instagram